### PR TITLE
INBOX from STDIN

### PR DESCRIPTION
**Pull request by rsd**
raul@nostromo:~/devel/hrm/work$ echo 1 11 1 2 10 | hrm -s test.bin 
Load 5 instructions .....
OUTBOX: 2
OUTBOX: 12
OUTBOX: 2
OUTBOX: 3
OUTBOX: 11
Executed 26 instructions

### CODE REVIEW

**Comment by cmatsuoka** [comment]
Merged, thanks.

**Comment by cmatsuoka** [comment]
I'm considering adding an additional option to specify the input list from the command, and also the expected output list and the initial memory state. Something like: ./hrm -i "1 2 3 4 5" -o "2 4 6 8 10" -m "9:0". If the expected output list is not specified, it simply runs the code. If it's specified and the output doesn't match, it would throw an exception.

**Comment by rsd** [comment]
or from a file.
it would simulate predefined test list in the hrm.
e.g. samples to avoid the code to just run with a few cases.

Can the memory be set in the assembler?

**Comment by cmatsuoka** [comment]
It could, but we also must be able to set it externally to be able to use the game clipboard asm source. I'll see how the original game specifies these values and do something similar.

**Pull request merged**
